### ISSUE TITLE
Tests fail with type mismatch

### ISSUE THREAD

**Issue by sirotopr** [grouzen/play2-jsend#3]
Currently all test are failing with an error similar to this:
```
play2-jsend/test/src/main/scala/play/api/libs/json/JSendSpec.scala:17: type mismatch;
  found   : play.api.libs.json.JsString
  required: play.api.libs.json.JsLookupResult
       (json \ "status") must be equalTo(JsString("success"))
```

I don't know what type we really want, and thus what should be the proper solution.

**Comment by grouzen** [comment]
I think, something like (json \ "status").as[String] would be enough. Seems like there are some changes in JSON API.
