### ISSUE TITLE
Publish to a repo such as Maven Central

### ISSUE THREAD

**Issue by sirotopr** [grouzen/play2-jsend#4]
It would be much handy if you could publish this library into some code repo such as Maven Central.

Right now the only way to use it is to publish it into the local repo. This adds complexity to build scripts and CI environments.

**Comment by grouzen** [comment]
Hi!

Actually, I've never done this. Maybe you can do this? 
And yeah, I think before publishing it to Maven we have to fix the bug with the `error` method.

**Comment by sirotopr** [comment]
It's better done by you, since you'll have to create an account and keep the corresponding credentials.

The process to publish into Maven Central (Sonatype Nexus) is straightforward, just follow their [OSSRH Guide](http://central.sonatype.org/pages/ossrh-guide.html).

BTW, whenever you publish a new version into Maven Central do add a new [release here on GitHub](https://github.com/grouzen/play2-jsend/releases). That way you will have a nice and public match between source code and publlshed binaries.

**Comment by grouzen** [comment]
Yeah, I'll do it in a few days! Thanks!

**Comment by grouzen** [comment]
I created a JIRA issue, waiting on a response...

**Comment by sirotopr** [comment]
Nice. They usually take just a couple of days. You should get an answer soon.

**Comment by grouzen** [comment]
Hi there!

I've got an error while publishing a signed artifact to Sonatype (using instructions described here: http://www.scala-sbt.org/0.13/docs/Using-Sonatype.html). Can't find any answer on google.
Could you help me with this, please?

> 
> [play2-jsend] $ publish-signed
> [warn] Binary version (2.10) for dependency org.scala-lang#scala-compiler;2.10.6
> [warn] 	in me.mnedokushev#play2-jsend_2.11;1.0.0 differs from Scala binary version in project (2.11).
> [warn] Binary version (2.10) for dependency org.scala-lang#scala-library;2.10.6
> [warn] 	in me.mnedokushev#play2-jsend_2.11;1.0.0 differs from Scala binary version in project (2.11).
> [warn] Binary version (2.10) for dependency org.scala-lang#scala-reflect;2.10.6
> [warn] 	in me.mnedokushev#play2-jsend_2.11;1.0.0 differs from Scala binary version in project (2.11).
> [warn] Binary version (2.10) for dependency org.scala-lang#scalap;2.10.6
> [warn] 	in me.mnedokushev#play2-jsend_2.11;1.0.0 differs from Scala binary version in project (2.11).
> [info] Wrote /home/grouzen/projects/play2-jsend/target/scala-2.11/play2-jsend_2.11-1.0.0.pom
> [info] :: delivering :: me.mnedokushev#play2-jsend_2.11;1.0.0 :: 1.0.0 :: release :: Thu Dec 22 08:45:38 EET 2016
> [info] 	delivering ivy file to /home/grouzen/projects/play2-jsend/target/scala-2.11/ivy-1.0.0.xml
> Please enter PGP passphrase (or ENTER to abort): ******************
> [trace] Stack trace suppressed: run last *:signedArtifacts for the full output.
> [error] (*:signedArtifacts) java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff
> 

> 
> play2-jsend] $ last *:signedArtifacts
> java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff
> 	at org.bouncycastle.openpgp.PGPSecretKeyRing.<init>(Unknown Source)
> 	at com.jsuereth.pgp.SecretKeyRing$.load(SecretKeyRing.scala:56)
> 	at com.jsuereth.pgp.SecretKeyRing$.load(SecretKeyRing.scala:52)
> 	at com.jsuereth.pgp.StreamingLoadable$class.loadFromFile(StreamingLoadable.scala:11)
> 	at com.jsuereth.pgp.SecretKeyRing$.loadFromFile(SecretKeyRing.scala:52)
> 	at com.jsuereth.pgp.PGP$.loadSecretKeyRing(package.scala:38)
> 	at com.jsuereth.pgp.cli.PgpStaticContext$class.secretKeyRing(context.scala:31)
> 	at com.typesafe.sbt.pgp.SbtPgpStaticContext.secretKeyRing(SbtPgpCommandContext.scala:8)
> 	at com.jsuereth.pgp.cli.DelegatingPgpStaticContext$class.secretKeyRing(context.scala:38)
> 	at com.typesafe.sbt.pgp.SbtPgpCommandContext.secretKeyRing(SbtPgpCommandContext.scala:13)
> 	at com.typesafe.sbt.pgp.BouncyCastlePgpSigner$$anonfun$sign$1.apply(PgpSigner.scala:42)
> 	at com.typesafe.sbt.pgp.BouncyCastlePgpSigner$$anonfun$sign$1.apply(PgpSigner.scala:37)
> 	at com.typesafe.sbt.pgp.Cache$class.withValue(SbtHelpers.scala:38)
> 	at com.typesafe.sbt.pgp.PasswordCache$.withValue(SbtHelpers.scala:55)
> 	at com.typesafe.sbt.pgp.SbtPgpCommandContext$$anonfun$1.apply(SbtPgpCommandContext.scala:34)
> 	at com.typesafe.sbt.pgp.SbtPgpCommandContext.retry(SbtPgpCommandContext.scala:42)
> 	at com.typesafe.sbt.pgp.SbtPgpCommandContext.withPassphrase(SbtPgpCommandContext.scala:31)
> 	at com.typesafe.sbt.pgp.BouncyCastlePgpSigner.sign(PgpSigner.scala:37)
> 	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$1$$anonfun$apply$1.apply(PgpSettings.scala:120)
> 	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$1$$anonfun$apply$1.apply(PgpSettings.scala:117)
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
> 	at scala.collection.immutable.Map$Map4.foreach(Map.scala:181)
> 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
> 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
> 	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$1.apply(PgpSettings.scala:117)
> 	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$1.apply(PgpSettings.scala:115)
> 	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
> 	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
> 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
> 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
> 	at sbt.std.Transform$$anon$4.work(System.scala:63)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
> 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
> 	at sbt.Execute.work(Execute.scala:237)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
> 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
> 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> [error] (*:signedArtifacts) java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff
>

**Comment by sirotopr** [comment]
Hi,

It's difficult to help without knowing for sure which configs you already made. Anyway, lets try.

1. Have you successfully generated your keypair ([command `pgp-cmd gen-key`](http://www.scala-sbt.org/sbt-pgp/usage.html#creating-a-key-pair))?
2. Is  `show */*:pgpSecretRing` pointing to the correct secret keyring file?

**Comment by grouzen** [comment]
I fixed the issue with the secret key. It was just empty. I ran `gpg --export-secret-keys > secring.gpg` and it helped, but there is one more problem I have - I can't send a key to one of the public gpg servers. Neither `pgp-cmd send-key` in sbt nor `gpg --send-keys` from CLI do not work. I tried to push the key on different servers and all of them tell me that "key not found".

**Comment by sirotopr** [comment]
You can submit a key directly through the keyservers' web interface. Just export it as ASCII (`gpg --export -a <keyid or email>`) and paste it in their form:
http://pgp.mit.edu/
http://pool.sks-keyservers.net/

**Comment by grouzen** [comment]
> http://pool.sks-keyservers.net/
> The requested URL /pks/add was not found on this server.
Funny.

pgp.mit.edu works!

Publishing is done!
https://oss.sonatype.org/service/local/repositories/releases/content/me/mnedokushev/

Thanks for your help!
Cheers!

**Comment by sirotopr** [comment]
Tested and working. Thanks!

I've just submitted a pull request that updates the README and closes this issue. Please accept it.

**Comment by grouzen** [comment]
Good job! Thanks!
